name=Flight Data Recorder Raspberry Pi RP2040
version=1.0.0
author=Rick Sparber
maintainer=Rick Sparber <rgsparber@aol.com>
sentence= Analog Flight Data Recorder upgraded with Raspberry Pi RP2040
paragraph= Eight Channel Analog Flight Data Recorder with peripherals
category=Sensors
url= 	none
depends=Flight Data Recorder, GPS, RunCam6, Iridium Modem
